server:
  port: 10001

spring:
  application:
    name: gateway-service
  output:
    ansi:
      enabled: always
  cloud:
    nacos:
      discovery:
        watch:
          enabled: true
        server-addr: nacos-server:18848
#        namespace: noop
        namespace: test
        group: NOOP_GROUP
        username: nacos
        password: nacos

    sentinel:
      transport:
        dashboard: 127.0.0.1:8182
        # 默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
      filter:
        enabled: false
      eager: true
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
        add-to-simple-url-handler-mapping: true
#      default-filters:
#        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

      discovery:
        locator:
          # 根据注册中心的服务自动生成路由
          enabled: true
          # 路由名转小写
          lower-case-service-id: true

management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

