server:
  port: 10001

spring:
  application:
    name: module-gateway
  output:
    ansi:
      enabled: always
  cloud:
    nacos:
      discovery:
        watch:
          enabled: true
        server-addr: 127.0.0.1:8848
        namespace: noop
        group: NOOP_GROUP
        username: nacos
        password: nacos

    sentinel:
      transport:
        dashboard: 127.0.0.1:8182
        # 默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
      filter:
        enabled: false
      eager: true
    gateway:
      discovery:
        locator:
          # 根据注册中心的服务自动生成路由
          enabled: true
          # 路由名转小写
          lower-case-service-id: true
#      routes:
#         用户模块
#      - id: user_route
#        uri: lb://module-user
#        predicates:
#          - Path=/user/**

management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
